sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.4.0
  - jruby-9.1.14.0
  - jruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
before_install: gem install bundler -v 1.13.7
