# vim:ts=2:sts=2:sw=2:et:
---
version: 2.0

jobs:
  "ruby-2.5":
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: gem install bundler -v "~> 2.0" --no-document
      - run: bundle install --path vendor/bundle
      - run:
          name: Run tests
          command: rake test

  "ruby-2.6":
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run: gem install bundler -v "~> 2.0" --no-document
      - run: bundle install --path vendor/bundle
      - run:
          name: Run tests
          command: rake test

  "ruby-2.7":
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - run: gem install bundler -v "~> 2.0" --no-document
      - run: bundle install --path vendor/bundle
      - run:
          name: Run tests
          command: rake test

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.5"
      - "ruby-2.6"
      - "ruby-2.7"
